# Communication channels {#channels}

The [Humans of rOpenSci](#humans) connect and contribute online across many
timezones. We carry out our work using multiple channels for one-way and
multi-way communications that involve different levels of commitment.

**GitHub** is the platform we use to host our software and documentation
projects using Git version control. Our **newsletter**, delivered once a month,
is the ideal way to stay informed without being overwhelmed by communication
channels. We use our social media accounts (**Mastodon**, **Bluesky**, and
**LinkedIn**), and our semi-open **Slack**, each for specific modes of making
announcements, promoting contributions from community members, asking and
answering questions about rOpenSci packages and recommended best practices,
knowledge-sharing and exploration of ideas, as well as more passive learning by
"listening" to community wisdom.

The following table lists every communication channel and its purpose. Below
that we describe how we use a few specific channels and provide some advice on
deciding whether a question you might have is one for rOpenSci or belongs in a
more general forum.

```{r}
#| results: "asis"
#| echo: false

library(tibble)
library(kableExtra)
tribble(
  ~Channel                                                               , ~Purpose                                                                                                                                                      ,
  "Website <https://ropensci.org/> <https://github.com/ropensci/roweb3>" , "Home of rOpenSci"                                                                                                                                            ,
  "[Newsletter](https://ropensci.org/news/)"                             , "A digest of R package news, use cases, blog posts, events, curated every month. [Subscribe](https://ropensci.org/news/) via RSS (XML), JSON feed, or email." ,
  "[Videos](https://vimeo.com/ropensci)"                                 , "Videos from past Community Calls on Vimeo"                                                                                                                   ,
  "[Mastodon](https://hachyderm.io/@rOpenSci)"                           , "Posts about rOpenSci software, use cases, blog posts, tech notes, events"                                                                                    ,
  "[Bluesky](https://bsky.app/profile/ropensci.org)"                     , "Posts about rOpenSci software, use cases, blog posts, tech notes, events"                                                                                    ,
  "[LinkedIn](https://www.linkedin.com/company/ropensci)"                , "Posts about rOpenSci software, use cases, blog posts, tech notes, events"                                                                                    ,
  "Video conferencing"                                                   , "Community Calls and remote co-working sessions on Zoom"                                                                                                      ,
  "[GitHub - ropensci](https://github.com/ropensci)"                     , "Mature R packages contributed by rOpenSci staff or community-contributed peer-reviewed packages; software peer review system; rOpenSci website"              ,
  "[GitHub - ropenscilabs](https://github.com/ropenscilabs)"             , "Experimental packages and code experiments from staff, collaborators, and participants of unconfs and related events"                                        ,
  "[GitHub - ropensci-org](https://github.com/ropensci-org)"             , "Non-code repositories like this guide, the blog guide, ideas for Community Calls"                                                                            ,
  "Slack"                                                                , "A semi-open space for communications among people who contribute to rOpenSci"                                                                                ,
  "Email: info at ropensci dot org"                                      , "To reach rOpenSci staff when other modes are not suitable"
) |>
  kable(format = "markdown")
```

## GitHub {#channels-github}

The majority of rOpenSci's work happens on GitHub. In this Guide we use terms
like "opening an issue" to refer to tracking ideas, enhancements, tasks, or bugs
in a project, and "making a pull request" to submit your proposed fix or new
feature. If you'd like some general information on the language and workflow of
GitHub, see [Collaborating with issues and pull
requests](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests).
To learn about Markdown formatting for interacting with others in issues and
pull requests see [Getting started with writing and formatting on
GitHub](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github).
For guidance on connecting R to GitHub we recommend Happy Git and GitHub for the
useR - [https://happygitwithr.com/](https://happygitwithr.com/).

## Slack {#channels-slack}

We use
[Slack](https://slack.com/intl/en-ca/help/articles/115004071768-What-is-Slack-)
as a semi-open space for communications among people who have made specific
contributions to rOpenSci. If you're interested in joining this space, all you
have to do is contribute to the community in one of the following ways:

- [co-host a coworking session](#coworking)
- [write post or tech note](#blog) for our blog
- [submit a package to software review](#devguide)
- [review a package](#devguide)
- [take over maintenance of an existing rOpenSci package](#packages)
- [present in a Community Call](#commcalls)
- [participate in the Champions Program](#champions)
- [participate in a translations project](#multilingual)
- participate in a project or research domain that rOpenSci is explicitly
  supporting or partnering with, such as Antarctic and Southern Ocean Research,
  or the Epiverse
- [participate in an unconf](#unconfs)

These contributions are not meant to be barriers to joining this space, just
ways of ensuring that members are intentional in their commitment. If you'd like
to join but aren't sure how to get started send us an email or ping us on social
media and we'll give you some suggestions.

By keeping this space by invitation we are also better able to curate a safe and
respective space for our community members.

People are normally invited to Slack by our Community Manager once they have
participated in one of the above activities. If we've missed you, contact us via
our [contact form](https://ropensci.org/contact/) and provide your full name and
email address.

The benefit of Slack is the ability to more directly access rOpenSci staff and
community members, including some more experienced folks in channels like
#software-review or #package-maintenance, or to watch for postings in #jobs.
People consider it an easier place to ask questions or explore ideas because
while it has over 500 members, it's not fully "in the open". [We actively
welcome new members](https://ropensci.org/blog/2017/07/18/value-of-welcome/) and
ensure that all conversations are collegial.

## How to get help {#channels-help}

There is an etiquette to getting help and asking questions. We focus on using,
developing, documenting code and infrastructure, and building community, as they
specifically align with [our mission](#mission).

People looking for more general R learning may refer to [RStudio
Education](https://education.rstudio.com/), [The
Carpentries](https://carpentries.org/), and the [Data Science Learning
Collective](https://dslc.io).

Read these posts if you have an R question: [Where to get help with your R
question?](https://masalmon.eu/2018/07/22/wheretogethelp/), by Maëlle Salmon;
[Getting help in R: do as I say, not as I've
done](https://sctyner.me/post/2019-2-17-rhelp/), by Samantha Tyner.

If you're asking for R help, reporting a bug, or requesting a new feature,
you're more likely to succeed if you include a good reproducible example, a
"reprex". There's a [well-documented package](https://reprex.tidyverse.org/) for
that including a video, and an rOpenSci Community Call - [How to Ask Questions
so they get Answered! Possibly by
Yourself!](https://ropensci.org/commcalls/2017-03-07/), with Jenny Bryan, JD
Long, and Scott Chamberlain.

## How to contribute?

- Read our [Code of Conduct](https://ropensci.org/code-of-conduct/) to ensure
  you are ready to participate
- **Follow rOpenSci on social media ([Mastodon](https://hachyderm.io/@rOpenSci),
  [Bluesky](https://bsky.app/profile/ropensci.org),
  [LinkedIn](https://www.linkedin.com/company/ropensci))**
- **Subscribe to our [Newsletter](https://ropensci.org/news/)**
- **Ask or answer questions**. Participate in discussions on GitHub or on Slack
