## Blog Posts {#blog-posts}

- TODO: ADD INTRO TEXT OR ADAPT FROM `3_proj_blog.qmd`

This list gives you a taste of some themes. Click on a topic below to see some
of our favorite examples.

```{r}
#| label: posts
#| results: "asis"
#| message: false

make_category <- function(category, posts) {
  post_list <- paste0(
    "<ul>",
    glue::glue_collapse(
      glue::glue_data(
        posts[posts$category == category, ],
        "<li> [{title}]({url}) {description}</li>",
        .na = ""
      ),
      sep = "\n"
    ),
    "</ul>"
  )

  glue::glue(
    "<li><details closed>\n<summary> <span title='Click to Expand'> {category} </span> </summary>\n{post_list}\n</details></li>"
  )
}
posts <- readr::read_csv2("blog_themes/blog_themes.csv")
cat(paste0(
  "<ul>",
  glue::glue_collapse(
    purrr::map_chr(unique(posts$category), make_category, posts = posts),
    sep = "\n"
  ),
  "</ul>"
))
```

There are many ways to explore our blog and tech notes content:

- Search by [tag](https://ropensci.org/tags/)
- Search by [author](https://ropensci.org/author/)
- Search by [date](https://ropensci.org/archive/)
- *ctrl/cmd-f* for a word in [archive page](https://ropensci.org/archive/) of
  post titles

### How to contribute?

- **Read [blog posts](https://ropensci.org/blog/) or [tech
  notes](https://ropensci.org/technotes/)**
- Did you find an article interesting or useful? **Share posts with your
  network**
- **Comment on a post to share your perspective or to ask a question.** Comments
  appear in our [public discussion forum](#channels).
- We love to hear stories about how people use our tools and resources. Have an
  idea for our blog? **Write a blog post or tech note**. Take a look at examples
  of posts above and on the [blog](https://ropensci.org/blog), browse the [Blog
  Guide](https://blogguide.ropensci.org/) to see what's involved, then contact
  our Community Manager via our [contact form](https://ropensci.org/contact/) to
  propose and discuss your idea.
