# Bibliography

We're always standing on the shoulders of giants, some of whom don't think of themselves as giants. 
The following resources together influenced the ideas, approach, design, tone, and content of the rOpenSci Community Contributing Guide. 

- [How to Contribute to Open Source](https://opensource.guide/how-to-contribute/). 
Authors: https://github.com/github/opensource.guide#acknowledgments

- Dan Sholler, Igor Steinmacher, Denae Ford, Mara Averick, Mike Hoye, Greg Wilson (2019). 
  [Ten simple rules for helping newcomers become contributors to open projects](https://doi.org/10.1371/journal.pcbi.1007296). 
  PLoS Comput Biol, 15(9), e1007296. https://doi.org/10.1371/journal.pcbi.1007296

- Tim O'Reilly (2004). [Open Source Paradigm Shift](https://www.oreilly.com/pub/a/tim/articles/paradigmshift_0504.html)

- The Astropy Project. [Contribute to Astropy](https://www.astropy.org/contribute.html)

- Jupyter Team. [Jupyter Contributing guide](https://jupyter.readthedocs.io/en/latest/contributing/content-contributor.html)

- RStudio. [RStudio Education](https://education.rstudio.com/)

- Nadia Eghbal (2020) [Working in Public: The Making and Maintenance of Open Source Software](https://press.stripe.com/#working-in-public). 
Stripe Press, San Francisco, CA.

- Mozilla Open Leadership Series. [Contributor Personas & Pathways](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/bring-on-contributors-using-personas-and-pathways/)

- Software Carpentry. [Carpentries Learner Profiles](https://software-carpentry.org/audience/)


# NEWS 

## 0.2.0

* Added NEWS chapter to appendix (#35)
* Update title on Zenodo (#45)
* Fix back-button issues (#44)
* Add cover and illustrator acknowledgement (#43)
* Update screenshots to match new rOpenSci website (#39)
* Update peer-review editor (#38)
* Fix Twitter link (#28)
* Minor text re-wording (e.g., #34)
* Switched to BS4 bookdown template
* Added new resources: Help Wanted Page, Use Cases Page, R-universe, Social Co-working
* Tweaked content
* Updated staff and community manager information

## 0.1.0 (2020-08-25)

* Initial release 🎉


