## Discover {#discover}

Stef to write preamble

Making data, tools more discoverable is part of our mission. This section is about finding and using rOpenSci’s packages. Discovering and using rOpenSci packages is a great way to contribute as without users, we have no reason to curate packages!  is a good first entryway, and then you are motivated to Connect and Learn, and then Influence and Help. Frequent gateway to rOpenSci is the "Use a package" action

**I want to:**

Discover packages I can use to facilitate my research 

*   [**Browse rOpenSci packages**](#packages)
*   [**Explore use cases for rOpenSci packages**](#usecases)
*   [**Read blog posts or tech notes**](#blog-usecase) about creative use cases for multiple rOpenSci packages
*   [**Read blog posts or tech notes**](#blog) about rOpenSci packages
*   Explore task views 
*   [**Follow rOpenSci on Twitter**](#channels)
*   [**Follow roknowtifier on Twitter**](#channels) to get notified about new packages and package updates
*   [**Subscribe to our Newsletter**](#channels)
*   [**Browse citations of rOpenSci packages**](#packages) to see what other researchers are using

Discover packages that facilitate access to open data

*   Use rOpenSci packages that access open data ([covid-ish blog post](https://ropensci.org/blog/2020/05/19/covid-19-open-data/))
*   {packages tag: open-data etc.}
*   {blog-tag: open etc.}

Discover resources on best practices for software development

*   [**Read the Dev Guide**](#devguide)
*   [**Read or ask questions**](#channels) in the “Best Practices” category in our forum or on Slack
*   [**Attend a Community Call**](#commcalls)
*   [**Watch recordings and read collaborative notes from past Community Calls**](#commcalls)
*   [**Read blog posts or tech notes**](#blog)

Discover resources on community building

*   [**Read blog posts or tech notes**](#blog), particularly those tagged with [“Welcome”](#blog-welcome) or [“unconf”](#blog-unconf)