## Learn {#learn}


rOpenSci provides avenues for new and more seasoned R users and developers to learn - 
from learning by reading and listening, to learning by doing. 
All in an atmosphere of trust, generosity, giving credit, and sharing gratitude. 
We focus here on using, developing, documenting code, and building community, 
as they specifically align with our mission. 
People looking for more general R learning may refer to [RStudio Education](https://education.rstudio.com/) and [The Carpentries](https://carpentries.org/). 

Scan the "I want to" statements below to find something that interests you. 
Click on any action under a statement to go to a description of the relevant rOpenSci resource with details on how to contribute.

**I want to:**

Be informed by reading and listening 

*   [Follow rOpenSci on Twitter](#channels)
*   [Subscribe to our Newsletter](#channels)
*   [Read blog posts or tech notes](#blog)
*   [Read the R-universe discussion](#runiverse)
*   [Attend a Community Call](#commcalls)
*   [Watch recordings and read collaborative notes from past Community Calls](#commcalls)
*   [Explore use cases](#usecases) shared by community members
*   [Follow discussions](#channels) about statistical software peer review, 
    best practices, and Q & A in the forum or on [Slack](#channels-slack)
*   [Join a coworking session](#coworking) and listen to questions and answers

Improve the reproducibility of my research and apply best practices in my work

*   [Use an rOpenSci package](#packages) if it does something you need instead of writing new code yourself
*   [Attend a Community Call](#commcalls) or 
    [watch recordings and read collaborative notes from past Community Calls](#commcalls). 
    Some past calls have covered these topics
*   [Read the Dev Guide](#devguide) and adopt some new best practices
*   [Read our book on Statistical Software Peer Review](#statsreview) to familiarize yourself with standards being developed
*   [Read or ask questions](#channels) in the "Best Practices" category in our forum or on [Slack](#channels-slack)
*   [Submit your package for peer review](#devguide) after determining whether it's in scope for rOpenSci


Improve my R and software development skills

*   Find new packages to try: [Browse rOpenSci packages](#packages), 
    [explore use cases](#usecases), [read blog posts or tech notes](#blog)
*   [Volunteer to review a package](#devguide)
*   [Seek community feedback on your package ideas in the "Packages" category in our forum](#channels-forum)
*   [Review package documentation](#packages)
*   [Address an issue](#issues). 
    Explore open issues in rOpenSci packages and consider submitting a fix. 
*   [Make a pull request](#packages) to add/fix examples or clarify package documentation 
*   [Write a vignette/article for a package](#packages)
*   [Share a use case](#usecases)
*   [Write a post about using rOpenSci packages](#packages) on your own blog
*   After learning something new, **write a blog post or tech note** to share your experiences 
    (see both the [Blog](#blog) and the [Blog Guide](#blogguide))
*   [Ask or answer questions](#channels) in the forum or on [Slack](#channels-slack)
*   [Volunteer to maintain or co-maintain a package](#devguide)
*   [Submit your package for peer review](#devguide) after determining whether it's in scope for rOpenSci
*   [Join a coworking session](#coworking) and ask questions of other developers


Learn how to review R code

*   [Read blog posts or tech notes](#blog) written by reviewers 
    (including some first-time reviewers) about their experiences 
*   [Read the Dev Guide](#devguide), especially the Reviewer Guide section
*   [Volunteer to review a package](#devguide). Learn by doing!


Learn how to get my package on CRAN

*   [Read the Dev Guide](#devguide), especially the CRAN Gotchas section
*   [Read or ask questions](#channels) in the "Packages" category in our forum or on
    [Slack](#channels-slack)
*   [Seek community feedback on your package ideas in the "Packages" category in our forum](#channels-forum)
*   [Submit your package for peer review](#devguide) after determining whether it's in scope for rOpenSci. The review process is very useful for making sure your package is also suitable for CRAN.


Learn about career paths in R and open science

*   [Meet the Humans of rOpenSci](#humans) and learn about their roles, 
    their research, career paths, and contributions
*   [Read blog posts or tech notes](#blog), particularly those tagged with "Interviews", 
    which feature experienced rOpenSci community members
*   [Browse the Jobs category](#channels) in our public forum or in [Slack](#channels-slack)
