## Build {#build}

Perhaps the roles people associate most with contributing to rOpenSci involve building and influencing the research software landscape in R. 
This includes things like having a stake in package development and documentation, 
discussions on new projects like developing standards for [statistical software peer review](#statsreview), 
or influencing the adoption of more open and reproducible research in your department, 
your institution, or your field. 

Scan the “I want to” statements below to find something that interests you. 
Click on any action under a statement to go to a description of the relevant rOpenSci resource with details on how to contribute.

**I want to:**

Improve and promote open science in my field

*   [Volunteer to review a package](#devguide)
*   Contribute to a task view. [Make a pull request](#taskviews) to add packages or details to an existing task view after discussing your approach with the maintainer
*   Develop a package and [submit it for peer review](#devguide) after determining whether it’s in scope for rOpenSci
*   [Recommend topics or speakers for Community Calls](#commcalls)
*   [Help organize a Community Call](#commcalls)
*   [Write a post about using rOpenSci packages](#packages) on your own blog
*   [Cite rOpenSci packages in manuscripts and presentations](#packages)
*   [Ensure your package is easily citable](#devguide)


Influence package development

*   [Volunteer to review a package](#devguide)
*   [Report a bug](#packages) in an rOpenSci package
*   [Make a feature request](#packages)
*   [Add a package idea to the Wishlist](#channels-forum) in the rOpenSci forums
*   [Address an issue](#issues). Explore open issues in rOpenSci packages and consider submitting a fix. 
*   [Make a pull request](#packages) to fix a bug or add a feature


Improve package documentation and examples

*   [Review documentation](#packages) and help the author by letting them know what’s unclear or [Make a pull request](#packages) to add/fix examples or to add/clarify documentation
*   [Write a vignette/article for a package](#packages)
*   [Share a use case](#usecases) or encourage your peers to do the same


Promote best practices for R development

*   [Engage with us on Twitter](#channels). 
    Amplify best practices from our social media to your networks
*   [Ask or answer questions](#channels) in the the “Best Practices” category in our forum or on [Slack](#channels-slack)
*   **Write a blog post or tech note** about the development of your rOpenSci package or your implementation of best practices (see both the [Blog](#blog) and the [Blog Guide](#blogguide))
*   [Recommend topics or speakers for Community Calls](#commcalls)
*   [Help organize a Community Call](#commcalls)
*   [Consider being a Community Host for a Coworking session](#coworking)


Promote software citations

*   [Cite rOpenSci packages in manuscripts and presentations](#packages) and encourage your colleagues to do the same
*   [Ensure your package is easily citable](#devguide)


Get more visibility and more users for my rOpenSci package

*   [Publish a paper about your package](#devguide)
*   [Write a post about using rOpenSci packages](#packages) on your own blog
*   Write a post or tech note about your package for the rOpenSci blog 
    (see both the [Blog](#blog) and the [Blog Guide](#blogguide))


Get people to work on open issues in my rOpenSci package

*   [Label your issues](#issues) to make them more discoverable
*   [Include future plans for your package](#issues) in the README.
*   [Request a co-maintainer for your package](#devguide). 
    Bringing on an additional maintainer can be a way to manage the volume of work, 
    work through issues, and increase package sustainability.
*   [Consider being a Community Host for a Coworking session](#coworking) and 
    supporting a mini code-a-thon.
