## Blog {#blog}

The rOpenSci blog contains both long form [blog posts](https://ropensci.org/blog/) and shorter [tech notes](https://ropensci.org/technotes). It’s a large, rich resource for learning about the R packages developed by staff and by community members and how people use them, the people and processes involved in our open software peer review system, and the value people get from being part of our community. We’ve published more than XXX posts since 2012. In the last two years, more than half of these were written by community members. The long form blog posts are for a broad readership, and the shorter tech notes include information on a software release with major new features, breaking changes, or significant new documentation for example. 

This list gives you a taste of some themes. Expand a topic below to see some of our favorite examples.

    [Welcome!](https://ropensci.org/tags/welcome/) Belonging to our community {#blog-welcome}

    [Interviews](https://ropensci.org/tags/interviews/) with rOpenSci staff and experienced community members {#blog-interviews}|

    Summaries of Community Calls {#blog-commcall}

    About our unconf events and projects {#blog-unconf}

    [About a peer-reviewed package](https://ropensci.org/tags/software-peer-review/) developed by the authors {#blog-packages}

    [Perspectives from software peer reviewers](https://ropensci.org/tags/reviewer/) {#blog-reviewers}

    Creative use cases for multiple rOpenSci packages {#blog-usecase}

*   [Getting your toes wet in R: Hydrology, meteorology, and more](https://ropensci.org/blog/2019/04/02/hydrology-task-view/)
*   [The Antarctic/Southern Ocean rOpenSci community](https://ropensci.org/blog/2018/11/13/antarctic/)
*   Make sure Maelle’s bird series is listed (check blog guide)

    About open data accessible through our packages {#blog-opendata}

    Using an rOpenSci resource, such as the Package Development Guide or a task view

    Major updates to key packages

    Contributing to or taking over maintenance of a package {#blog-maintenance}

    Describe an unsolved problem and a call to action

    [Reproducibility](https://ropensci.org/tags/reproducibility/) and [Reproducible Research](https://ropensci.org/tags/reproducible-research/) {#blog-reproducibility}


There are many ways to explore our blog and tech notes content:

*   Search by [tag](https://ropensci.org/tags/)
*   Search by [author](https://ropensci.org/author/)
*   Search by [date](https://ropensci.org/archive/)
*   _ctrl/cmd-f_ for a word in [archive page](https://ropensci.org/archive/) of post titles


### How to contribute? 

*   **Read [blog posts](https://ropensci.org/blog/) or [tech notes](https://ropensci.org/technotes/)**
*   Did you find an article interesting or useful? **Share posts with your network**
*   **Comment on a post to share your perspective or to ask a question.** Comments appear in our [public discussion forum](#channels).
*   We love to hear stories about how people use our tools and resources. Have an idea for our blog? **Write a blog post or tech note**. Take a look at examples of posts above and on the [blog](https://ropensci.org/blog), browse the [Blog Guide](https://blogguide.ropensci.org/) to see what’s involved, then contact our Community Manager, Stefanie Butland, via [Slack](#channels-slack) or our [contact form](https://ropensci.org/contact/) to propose and discuss your idea.
