## The Dev Guide: Development, maintenance, and peer review of rOpenSci packages {#devguide}

Our online guide “[rOpenSci Packages: Development, Maintenance, and Peer Review](https://devguide.ropensci.org/)” a.k.a. the “Dev Guide”, is a resource for authors, maintainers, reviewers and editors of rOpenSci packages.

rOpenSci has been running a software peer review system since 2015 to combine the best of academic peer review with software review. Having robust and reliable software tools is an important component of supporting open science and reproducible research. The Dev Guide was developed as a resource to help support and streamline these efforts and to promote best practices. It contains a huge amount of information including:

*    Standards and best practices for building packages, such as [creating and testing packages, continuous integration](https://devguide.ropensci.org/ci.html) and [security](https://devguide.ropensci.org/package-development-security-best-practices.html).
*   [The peer review process](https://devguide.ropensci.org/softwarereviewintro.html), including policies and guides for authors and reviewers 

Are you wondering **what it’s like to review a package for the first time**, or how long it might take? Explore the Dev Guide sections on [Why submit your package to rOpenSci? a](https://devguide.ropensci.org/softwarereviewintro.html#whysubmit)nd [Guide for Reviewers](https://devguide.ropensci.org/reviewerguide.html). Read [blog posts with the “reviewer” tag](https://ropensci.org/tags/reviewer/). Many people review an R package before ever making one. Check out the [list of past reviewers](https://devguide.ropensci.org/softwarereviewintro.html#reviewers). Maybe you know one of them and can ask about their experience. 

> As a useR, you are qualified as a potential package reviewer if you have some appreciation for what makes your favourite packages useful.
> 
> [Miles McBain in "Where is the value in package peer review?"](https://ropensci.org/blog/2018/04/06/peer-review-value/)

If you’re **interested in submitting a package for peer-review**, read the Dev Guide section [Why review packages for rOpenSci?](https://devguide.ropensci.org/softwarereviewintro.html#whyreview) or read [blog posts with the “software-peer-review” tag](https://ropensci.org/tags/software-peer-review/) to get the perspectives of authors whose packages have passed peer review as well as learn about the process itself.

Once you’ve submitted your package and an editor has assigned reviewers, you and the reviewers will be invited to join rOpenSci’s [Slack](#channels-slack) workspace where you can connect more directly with members of the rOpenSci community, including other reviewers, package authors, users, and the rOpenSci staff and leadership team.

When you submit your package for review, **consider also publishing a journal article about your package**. We have collaborative agreements with two journals. If you choose to submit an article to the [Journal of Open Source Software (JOSS)](https://joss.theoj.org/), it will be [evaluated by JOSS](https://devguide.ropensci.org/guide-for-authors.html) based on the completed rOpenSci review. To submit to [Methods in Ecology and Evolution](https://ropensci.org/blog/2017/11/29/review-collaboration-mee/), you can submit to a joint review process whereby your package is reviewed by rOpenSci, followed by a fast-tracked review of the manuscript by Methods in Ecology and Evolution.

Finally, make sure your package is easily citable to get credit for all your hard work! Use the `use_citation()` function from the usethis package to add a `CITATION` file so users can use `citation("yourpackage")` to easily find how to best cite your package. It's also useful to add section to your `README` letting users know how you'd like them to cite your package. 

Sometimes an rOpenSci package maintainer finds that maintaining a package is no longer feasible for them. When that happens, we work hard to find new maintainers. If you think you might be interested, the Dev Guide Chapter on [Changing Maintainers](https://devguide.ropensci.org/changing-maintainers.html) is a good place to start. If taking on a whole package seems like a bit much, check out our [“Issues”](#issues) section here to find specific issues you could help tackle in a package.

For the big picture, watch the video of Noam Ross’s useR! 2020 keynote, “[Peer-Reviewing R Code: Where We've Been and Where We're Going at rOpenSci](https://youtu.be/iJnn_9xKkqk)” 

Read how our Dev Guide has been used in the wild in a manuscript review: [When Standards Go Wild - Software Review for a Manuscript](https://ropensci.org/blog/2019/04/18/wild-standards/), and in the core curriculum of a Master of Data Science program: [Using rOpenSci Software Peer Review Guidelines for Teaching](https://ropensci.org/blog/2019/08/27/software-peer-review-guidelines-for-teaching/).


### How to contribute

*   **Learn about reviewer guidelines**. Read the [Guide for Reviewers](https://devguide.ropensci.org/reviewerguide.html)
*   **Volunteer to review a package**. Fill out [this form to get started](https://ropensci.org/onboarding/). You’ll be contacted by an editor when a submitted package fits your profile. First-time reviewers are paired with more experienced reviewers and can request guidance from an editor.
*   **Submit your package for peer review**. Read the [Guide for Authors](https://devguide.ropensci.org/guide-for-authors.html) and then submit a pre-submission inquiry to the [GitHub repository where reviews take place](https://github.com/ropensci/software-review/issues) to see if your package is in scope for rOpenSci.
*   **Publish a paper about your package**. See above for our collaborations with the [Journal of Open Source Software (JOSS)](https://joss.theoj.org/) and [Methods in Ecology and Evolution](https://ropensci.org/blog/2017/11/29/review-collaboration-mee/).
*   **Acknowledge your reviewers** in your package DESCRIPTION (with their consent). Read about this in [Thanking Your Reviewers: Gratitude through Semantic Metadata](https://ropensci.org/blog/2018/03/16/thanking-reviewers-in-metadata/). 
*   Add a CITATION file to **ensure your package is easily citable**
*   **Request a co-maintainer for your package**. Post a request in the  #package-maintenance [Slack channel](#channels-Slack).
*   **Volunteer to maintain a package**. Check out the [rOpenSci Newsletter](https://news.ropensci.org/), the last section is a “Call For Maintainers” and consists of a list of packages specifically looking for maintainers.
